version: '3.1'
services:
   db:
     image: mysql:latest
     container_name: first-db
     restart: always
     volumes:
      - /Users/chandramohan.m/Mysql/data:/var/lib/mysql
     environment:
      MYSQL_ROOT_PASSWORD: 'test_pass'
      MYSQL_USER: 'test'
      MYSQL_PASS: 'pass'
     ports:
      - "3306:3306"
     depends_on:
        - webserver 
  #Nginx Service
   webserver:
     image: nginx:alpine
     container_name: webserver
     restart: unless-stopped
     ports:
      - "80:80"
     volumes:
      - /Users/chandramohan.m/index.html:/usr/share/nginx/html/index.html
     ports:
      - "80:80" 
   redis:
      image: 'bitnami/redis:latest'
      container_name: redis
      volumes:
          - /Users/chandramohan.m/Redis/data:/bitnami/redis/data
      environment:
        ALLOW_EMPTY_PASSWORD: yes
      ports:
        - "6379:6379"  
      depends_on:
        - db        

   